[package]
name = "sqs-reader"
version = "0.1.0"
authors = ["Frank Murphy <fmurphy@instructure.com>"]

[[bin]]
name = "sqs-reader"
path = "src/main.rs"

[dependencies]
rusoto_core = "0.33.0"
rusoto_sqs = "0.33.0"
serde_json = "1.0"
